/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MetalAnalysisResult {
  'copperProbability' : bigint,
  'nickelProbability' : bigint,
  'zincProbability' : bigint,
  'purityEstimate' : [] | [bigint],
  'titaniumProbability' : bigint,
  'goldProbability' : bigint,
  'metalType' : MetalType,
  'aluminiumProbability' : bigint,
  'confidenceScore' : bigint,
  'estimatedValueUSD' : [] | [bigint],
  'leadProbability' : bigint,
  'disclaimer' : string,
  'analysisTimestamp' : bigint,
  'silverProbability' : bigint,
  'steelProbability' : bigint,
}
export interface MetalPrice {
  'lastUpdated' : bigint,
  'pricePerGramUSD' : number,
}
export interface MetalPrices {
  'gold' : MetalPrice,
  'lead' : MetalPrice,
  'zinc' : MetalPrice,
  'aluminium' : MetalPrice,
  'titanium' : MetalPrice,
  'steel' : MetalPrice,
  'nickel' : MetalPrice,
  'silver' : MetalPrice,
  'copper' : MetalPrice,
}
export type MetalType = { 'gold' : null } |
  { 'lead' : null } |
  { 'zinc' : null } |
  { 'aluminium' : null } |
  { 'titanium' : null } |
  { 'steel' : null } |
  { 'nickel' : null } |
  { 'silver' : null } |
  { 'copper' : null } |
  { 'autoDetect' : null } |
  { 'unknown' : null };
export interface ScanRecord {
  'id' : bigint,
  'analysisResult' : MetalAnalysisResult,
  'user' : Principal,
  'timestamp' : bigint,
  'weightGrams' : [] | [number],
  'dimensions' : [] | [[number, number, number]],
  'selectedMetal' : MetalType,
  'images' : Array<ExternalBlob>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentMetalPrices' : ActorMethod<[], MetalPrices>,
  'getScanById' : ActorMethod<[Principal, bigint], ScanRecord>,
  'getScanHistory' : ActorMethod<[Principal], Array<ScanRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserScanCount' : ActorMethod<[Principal], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveScan' : ActorMethod<
    [
      MetalType,
      Array<ExternalBlob>,
      [] | [number],
      [] | [[number, number, number]],
      MetalAnalysisResult,
    ],
    bigint
  >,
  'updateMetalPrices' : ActorMethod<[MetalPrices], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];