/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MetalPrice = IDL.Record({
  'lastUpdated' : IDL.Int,
  'pricePerGramUSD' : IDL.Float64,
});
export const MetalPrices = IDL.Record({
  'gold' : MetalPrice,
  'lead' : MetalPrice,
  'zinc' : MetalPrice,
  'aluminium' : MetalPrice,
  'titanium' : MetalPrice,
  'steel' : MetalPrice,
  'nickel' : MetalPrice,
  'silver' : MetalPrice,
  'copper' : MetalPrice,
});
export const MetalType = IDL.Variant({
  'gold' : IDL.Null,
  'lead' : IDL.Null,
  'zinc' : IDL.Null,
  'aluminium' : IDL.Null,
  'titanium' : IDL.Null,
  'steel' : IDL.Null,
  'nickel' : IDL.Null,
  'silver' : IDL.Null,
  'copper' : IDL.Null,
  'autoDetect' : IDL.Null,
  'unknown' : IDL.Null,
});
export const MetalAnalysisResult = IDL.Record({
  'copperProbability' : IDL.Nat,
  'nickelProbability' : IDL.Nat,
  'zincProbability' : IDL.Nat,
  'purityEstimate' : IDL.Opt(IDL.Nat),
  'titaniumProbability' : IDL.Nat,
  'goldProbability' : IDL.Nat,
  'metalType' : MetalType,
  'aluminiumProbability' : IDL.Nat,
  'confidenceScore' : IDL.Nat,
  'estimatedValueUSD' : IDL.Opt(IDL.Nat),
  'leadProbability' : IDL.Nat,
  'disclaimer' : IDL.Text,
  'analysisTimestamp' : IDL.Int,
  'silverProbability' : IDL.Nat,
  'steelProbability' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ScanRecord = IDL.Record({
  'id' : IDL.Nat,
  'analysisResult' : MetalAnalysisResult,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'weightGrams' : IDL.Opt(IDL.Float64),
  'dimensions' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64)),
  'selectedMetal' : MetalType,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentMetalPrices' : IDL.Func([], [MetalPrices], ['query']),
  'getScanById' : IDL.Func([IDL.Principal, IDL.Nat], [ScanRecord], ['query']),
  'getScanHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ScanRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserScanCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveScan' : IDL.Func(
      [
        MetalType,
        IDL.Vec(ExternalBlob),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64)),
        MetalAnalysisResult,
      ],
      [IDL.Nat],
      [],
    ),
  'updateMetalPrices' : IDL.Func([MetalPrices], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MetalPrice = IDL.Record({
    'lastUpdated' : IDL.Int,
    'pricePerGramUSD' : IDL.Float64,
  });
  const MetalPrices = IDL.Record({
    'gold' : MetalPrice,
    'lead' : MetalPrice,
    'zinc' : MetalPrice,
    'aluminium' : MetalPrice,
    'titanium' : MetalPrice,
    'steel' : MetalPrice,
    'nickel' : MetalPrice,
    'silver' : MetalPrice,
    'copper' : MetalPrice,
  });
  const MetalType = IDL.Variant({
    'gold' : IDL.Null,
    'lead' : IDL.Null,
    'zinc' : IDL.Null,
    'aluminium' : IDL.Null,
    'titanium' : IDL.Null,
    'steel' : IDL.Null,
    'nickel' : IDL.Null,
    'silver' : IDL.Null,
    'copper' : IDL.Null,
    'autoDetect' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const MetalAnalysisResult = IDL.Record({
    'copperProbability' : IDL.Nat,
    'nickelProbability' : IDL.Nat,
    'zincProbability' : IDL.Nat,
    'purityEstimate' : IDL.Opt(IDL.Nat),
    'titaniumProbability' : IDL.Nat,
    'goldProbability' : IDL.Nat,
    'metalType' : MetalType,
    'aluminiumProbability' : IDL.Nat,
    'confidenceScore' : IDL.Nat,
    'estimatedValueUSD' : IDL.Opt(IDL.Nat),
    'leadProbability' : IDL.Nat,
    'disclaimer' : IDL.Text,
    'analysisTimestamp' : IDL.Int,
    'silverProbability' : IDL.Nat,
    'steelProbability' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ScanRecord = IDL.Record({
    'id' : IDL.Nat,
    'analysisResult' : MetalAnalysisResult,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
    'weightGrams' : IDL.Opt(IDL.Float64),
    'dimensions' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64)),
    'selectedMetal' : MetalType,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentMetalPrices' : IDL.Func([], [MetalPrices], ['query']),
    'getScanById' : IDL.Func([IDL.Principal, IDL.Nat], [ScanRecord], ['query']),
    'getScanHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ScanRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserScanCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveScan' : IDL.Func(
        [
          MetalType,
          IDL.Vec(ExternalBlob),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64)),
          MetalAnalysisResult,
        ],
        [IDL.Nat],
        [],
      ),
    'updateMetalPrices' : IDL.Func([MetalPrices], [], []),
  });
};

export const init = ({ IDL }) => { return []; };